// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation-participant.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipantToConversation = `-- name: AddParticipantToConversation :one
INSERT INTO "ConversationParticipants" (
  conversation_id,
  user_id
) VALUES (
  $1, $2
)
RETURNING conversation_participants_id, conversation_id, user_id, last_read_at, joined_at
`

type AddParticipantToConversationParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) AddParticipantToConversation(ctx context.Context, arg AddParticipantToConversationParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipantToConversation, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationParticipantsID,
		&i.ConversationID,
		&i.UserID,
		&i.LastReadAt,
		&i.JoinedAt,
	)
	return i, err
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT 
  u.id,
  u.username,
  u.email,
  u.profile_picture_url,
  u.is_online,
  cp.last_read_at,
  cp.joined_at
FROM "ConversationParticipants" cp
INNER JOIN "Users" u ON cp.user_id = u.id
WHERE cp.conversation_id = $1
`

type GetConversationParticipantsRow struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	IsOnline          bool               `json:"is_online"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	JoinedAt          time.Time          `json:"joined_at"`
}

func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID int64) ([]GetConversationParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversationParticipantsRow{}
	for rows.Next() {
		var i GetConversationParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.ProfilePictureUrl,
			&i.IsOnline,
			&i.LastReadAt,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) as unread_count
FROM "Messages" m
INNER JOIN "ConversationParticipants" cp 
  ON m.conversation_id = cp.conversation_id
WHERE cp.conversation_id = $1 
  AND cp.user_id = $2
  AND m.sent_at > COALESCE(cp.last_read_at, '1970-01-01'::timestamp)
`

type GetUnreadCountParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, arg.ConversationID, arg.UserID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const isUserInConversation = `-- name: IsUserInConversation :one
SELECT EXISTS(
  SELECT 1 FROM "ConversationParticipants"
  WHERE conversation_id = $1 AND user_id = $2
) as is_participant
`

type IsUserInConversationParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) IsUserInConversation(ctx context.Context, arg IsUserInConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInConversation, arg.ConversationID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const removeParticipantFromConversation = `-- name: RemoveParticipantFromConversation :exec
DELETE FROM "ConversationParticipants"
WHERE conversation_id = $1 AND user_id = $2
`

type RemoveParticipantFromConversationParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) RemoveParticipantFromConversation(ctx context.Context, arg RemoveParticipantFromConversationParams) error {
	_, err := q.db.Exec(ctx, removeParticipantFromConversation, arg.ConversationID, arg.UserID)
	return err
}

const updateLastReadAt = `-- name: UpdateLastReadAt :exec
UPDATE "ConversationParticipants"
SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateLastReadAtParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error {
	_, err := q.db.Exec(ctx, updateLastReadAt, arg.ConversationID, arg.UserID)
	return err
}
