// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ConversationsID uuid.UUID        `json:"conversations_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ConversationParticipant struct {
	ConversationParticipantsID uuid.UUID `json:"conversation_participants_id"`
	ConversationID             uuid.UUID `json:"conversation_id"`
	UserID                     uuid.UUID `json:"user_id"`
	// For read receipts
	LastReadAt pgtype.Timestamp `json:"last_read_at"`
	JoinedAt   pgtype.Timestamp `json:"joined_at"`
}

type Message struct {
	MessagesID     uuid.UUID `json:"messages_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	// E2E encrypted message
	EncryptedContent string `json:"encrypted_content"`
	// For idempotency/deduplication
	ClientMessageID string           `json:"client_message_id"`
	SentAt          pgtype.Timestamp `json:"sent_at"`
}

type TypingIndicator struct {
	TypingIndicatorsID uuid.UUID        `json:"typing_indicators_id"`
	ConversationID     uuid.UUID        `json:"conversation_id"`
	UserID             uuid.UUID        `json:"user_id"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	// For E2E encryption
	PublicKey         string           `json:"public_key"`
	ProfilePictureUrl pgtype.Text      `json:"profile_picture_url"`
	IsOnline          pgtype.Bool      `json:"is_online"`
	LastSeenAt        pgtype.Timestamp `json:"last_seen_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}
