// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipantToConversation(ctx context.Context, arg AddParticipantToConversationParams) (ConversationParticipant, error)
	CleanupStaleTypingIndicators(ctx context.Context) error
	CreateConversation(ctx context.Context) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessage(ctx context.Context, messagesID uuid.UUID) error
	FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (uuid.UUID, error)
	GetConversationByID(ctx context.Context, conversationsID uuid.UUID) (Conversation, error)
	GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error)
	GetConversationParticipants(ctx context.Context, conversationID uuid.UUID) ([]GetConversationParticipantsRow, error)
	GetConversationWithParticipants(ctx context.Context, conversationsID uuid.UUID) ([]GetConversationWithParticipantsRow, error)
	GetLatestMessage(ctx context.Context, conversationID uuid.UUID) (GetLatestMessageRow, error)
	GetMessageByClientID(ctx context.Context, clientMessageID string) (Message, error)
	GetMessageByID(ctx context.Context, messagesID uuid.UUID) (GetMessageByIDRow, error)
	GetMessageCount(ctx context.Context, conversationID uuid.UUID) (int64, error)
	GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]GetMessagesBeforeRow, error)
	GetMessagesSince(ctx context.Context, arg GetMessagesSinceParams) ([]GetMessagesSinceRow, error)
	GetOnlineUsers(ctx context.Context) ([]GetOnlineUsersRow, error)
	GetOrCreateDirectConversation(ctx context.Context, arg GetOrCreateDirectConversationParams) (uuid.UUID, error)
	GetTypingUsers(ctx context.Context, conversationID uuid.UUID) ([]GetTypingUsersRow, error)
	GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error)
	GetUserConversationsWithLastMessage(ctx context.Context, arg GetUserConversationsWithLastMessageParams) ([]GetUserConversationsWithLastMessageRow, error)
	IsUserInConversation(ctx context.Context, arg IsUserInConversationParams) (bool, error)
	RemoveParticipantFromConversation(ctx context.Context, arg RemoveParticipantFromConversationParams) error
	RemoveTypingIndicator(ctx context.Context, arg RemoveTypingIndicatorParams) error
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]SearchUsersByUsernameRow, error)
	SetTypingIndicator(ctx context.Context, arg SetTypingIndicatorParams) (TypingIndicator, error)
	UpdateConversationTimestamp(ctx context.Context, conversationsID uuid.UUID) error
	UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error
	UpdateUserOnlineStatus(ctx context.Context, arg UpdateUserOnlineStatusParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
