// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stat.sql

package db

import (
	"context"
)

const getOnlineUsersCount = `-- name: GetOnlineUsersCount :one
SELECT COUNT(*) as total
FROM "Users"
WHERE is_online = true
`

func (q *Queries) GetOnlineUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOnlineUsersCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTotalConversations = `-- name: GetTotalConversations :one
SELECT COUNT(*) as total
FROM "Conversations"
`

func (q *Queries) GetTotalConversations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalConversations)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTotalMessages = `-- name: GetTotalMessages :one
SELECT COUNT(*) as total
FROM "Messages"
`

func (q *Queries) GetTotalMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalMessages)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTotalUsers = `-- name: GetTotalUsers :one
SELECT COUNT(*) as total
FROM "Users"
`

func (q *Queries) GetTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}
