// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: type-indicators.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupStaleTypingIndicators = `-- name: CleanupStaleTypingIndicators :exec
DELETE FROM "TypingIndicators"
WHERE started_at < now() - interval '10 seconds'
`

func (q *Queries) CleanupStaleTypingIndicators(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupStaleTypingIndicators)
	return err
}

const getTypingUsers = `-- name: GetTypingUsers :many
SELECT 
  u.id,
  u.username,
  u.profile_picture_url,
  ti.started_at
FROM "TypingIndicators" ti
INNER JOIN "Users" u ON ti.user_id = u.id
WHERE ti.conversation_id = $1
  AND ti.started_at > now() - interval '10 seconds'
`

type GetTypingUsersRow struct {
	ID                int64            `json:"id"`
	Username          string           `json:"username"`
	ProfilePictureUrl pgtype.Text      `json:"profile_picture_url"`
	StartedAt         pgtype.Timestamp `json:"started_at"`
}

func (q *Queries) GetTypingUsers(ctx context.Context, conversationID int64) ([]GetTypingUsersRow, error) {
	rows, err := q.db.Query(ctx, getTypingUsers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTypingUsersRow{}
	for rows.Next() {
		var i GetTypingUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ProfilePictureUrl,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTypingIndicator = `-- name: RemoveTypingIndicator :exec
DELETE FROM "TypingIndicators"
WHERE conversation_id = $1 AND user_id = $2
`

type RemoveTypingIndicatorParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) RemoveTypingIndicator(ctx context.Context, arg RemoveTypingIndicatorParams) error {
	_, err := q.db.Exec(ctx, removeTypingIndicator, arg.ConversationID, arg.UserID)
	return err
}

const setTypingIndicator = `-- name: SetTypingIndicator :one
INSERT INTO "TypingIndicators" (
  conversation_id,
  user_id
) VALUES (
  $1, $2
)
ON CONFLICT (conversation_id, user_id) 
DO UPDATE SET started_at = now()
RETURNING typing_indicators_id, conversation_id, user_id, started_at
`

type SetTypingIndicatorParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) SetTypingIndicator(ctx context.Context, arg SetTypingIndicatorParams) (TypingIndicator, error) {
	row := q.db.QueryRow(ctx, setTypingIndicator, arg.ConversationID, arg.UserID)
	var i TypingIndicator
	err := row.Scan(
		&i.TypingIndicatorsID,
		&i.ConversationID,
		&i.UserID,
		&i.StartedAt,
	)
	return i, err
}
