// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE "Users"
SET is_banned = true,
    banned_at = now(),
    banned_reason = $2
WHERE id = $1
`

type BanUserParams struct {
	ID           int64       `json:"id"`
	BannedReason pgtype.Text `json:"banned_reason"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.ID, arg.BannedReason)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "Users" (
  username,
  email,
  password_hash,
  role,
  profile_picture_url
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, username, email, password_hash, profile_picture_url, is_online, last_seen_at, role, is_banned, banned_at, banned_reason, created_at
`

type CreateUserParams struct {
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	PasswordHash      string      `json:"password_hash"`
	Role              string      `json:"role"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ProfilePictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password_hash, profile_picture_url, is_online, last_seen_at, role, is_banned, banned_at, banned_reason, created_at FROM "Users" 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.ProfilePictureUrl,
			&i.IsOnline,
			&i.LastSeenAt,
			&i.Role,
			&i.IsBanned,
			&i.BannedAt,
			&i.BannedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnlineUsers = `-- name: GetOnlineUsers :many
SELECT id, username, profile_picture_url, last_seen_at
FROM "Users"
WHERE is_online = true
ORDER BY last_seen_at DESC
`

type GetOnlineUsersRow struct {
	ID                int64            `json:"id"`
	Username          string           `json:"username"`
	ProfilePictureUrl pgtype.Text      `json:"profile_picture_url"`
	LastSeenAt        pgtype.Timestamp `json:"last_seen_at"`
}

func (q *Queries) GetOnlineUsers(ctx context.Context) ([]GetOnlineUsersRow, error) {
	rows, err := q.db.Query(ctx, getOnlineUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOnlineUsersRow{}
	for rows.Next() {
		var i GetOnlineUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ProfilePictureUrl,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, profile_picture_url, is_online, last_seen_at, role, is_banned, banned_at, banned_reason, created_at FROM "Users"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, profile_picture_url, is_online, last_seen_at, role, is_banned, banned_at, banned_reason, created_at FROM "Users"
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, profile_picture_url, is_online, last_seen_at, role, is_banned, banned_at, banned_reason, created_at FROM "Users"
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, username, email, profile_picture_url, is_online
FROM "Users"
WHERE username ILIKE $1
LIMIT $2
`

type SearchUsersByUsernameParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
}

type SearchUsersByUsernameRow struct {
	ID                int64       `json:"id"`
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	IsOnline          pgtype.Bool `json:"is_online"`
}

func (q *Queries) SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]SearchUsersByUsernameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsername, arg.Username, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByUsernameRow{}
	for rows.Next() {
		var i SearchUsersByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.ProfilePictureUrl,
			&i.IsOnline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE "Users"
SET is_banned = false,
    banned_at = NULL,
    banned_reason = NULL
WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}

const updateUserOnlineStatus = `-- name: UpdateUserOnlineStatus :exec
UPDATE "Users"
SET is_online = $2,
    last_seen_at = CASE WHEN $2 = false THEN now() ELSE last_seen_at END
WHERE id = $1
`

type UpdateUserOnlineStatusParams struct {
	ID       int64       `json:"id"`
	IsOnline pgtype.Bool `json:"is_online"`
}

func (q *Queries) UpdateUserOnlineStatus(ctx context.Context, arg UpdateUserOnlineStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserOnlineStatus, arg.ID, arg.IsOnline)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE "Users"
SET profile_picture_url = COALESCE($2, profile_picture_url),
    username = COALESCE($3, username)
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID                int64       `json:"id"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	Username          string      `json:"username"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.ProfilePictureUrl, arg.Username)
	return err
}
