// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "Users" (
  username,
  email,
  password_hash,
  public_key,
  profile_picture_url
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, username, email, password_hash, public_key, profile_picture_url, is_online, last_seen_at, created_at
`

type CreateUserParams struct {
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	PasswordHash      string      `json:"password_hash"`
	PublicKey         string      `json:"public_key"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.PublicKey,
		arg.ProfilePictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOnlineUsers = `-- name: GetOnlineUsers :many
SELECT id, username, profile_picture_url, last_seen_at
FROM "Users"
WHERE is_online = true
ORDER BY last_seen_at DESC
`

type GetOnlineUsersRow struct {
	ID                uuid.UUID        `json:"id"`
	Username          string           `json:"username"`
	ProfilePictureUrl pgtype.Text      `json:"profile_picture_url"`
	LastSeenAt        pgtype.Timestamp `json:"last_seen_at"`
}

func (q *Queries) GetOnlineUsers(ctx context.Context) ([]GetOnlineUsersRow, error) {
	rows, err := q.db.Query(ctx, getOnlineUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOnlineUsersRow{}
	for rows.Next() {
		var i GetOnlineUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ProfilePictureUrl,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, public_key, profile_picture_url, is_online, last_seen_at, created_at FROM "Users"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, public_key, profile_picture_url, is_online, last_seen_at, created_at FROM "Users"
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, public_key, profile_picture_url, is_online, last_seen_at, created_at FROM "Users"
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.ProfilePictureUrl,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, username, email, profile_picture_url, is_online
FROM "Users"
WHERE username ILIKE $1
LIMIT $2
`

type SearchUsersByUsernameParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
}

type SearchUsersByUsernameRow struct {
	ID                uuid.UUID   `json:"id"`
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	IsOnline          pgtype.Bool `json:"is_online"`
}

func (q *Queries) SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]SearchUsersByUsernameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsername, arg.Username, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByUsernameRow{}
	for rows.Next() {
		var i SearchUsersByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.ProfilePictureUrl,
			&i.IsOnline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserOnlineStatus = `-- name: UpdateUserOnlineStatus :exec
UPDATE "Users"
SET is_online = $2,
    last_seen_at = CASE WHEN $2 = false THEN now() ELSE last_seen_at END
WHERE id = $1
`

type UpdateUserOnlineStatusParams struct {
	ID       uuid.UUID   `json:"id"`
	IsOnline pgtype.Bool `json:"is_online"`
}

func (q *Queries) UpdateUserOnlineStatus(ctx context.Context, arg UpdateUserOnlineStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserOnlineStatus, arg.ID, arg.IsOnline)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE "Users"
SET profile_picture_url = COALESCE($2, profile_picture_url),
    username = COALESCE($3, username)
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID                uuid.UUID   `json:"id"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	Username          string      `json:"username"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.ProfilePictureUrl, arg.Username)
	return err
}
